### ISSUE TITLE
Dataset of organisations

### ISSUE THREAD

**Issue by Fred-certeu** [OpenCTI-Platform/datasets#4]
Like there is a data set of sectors and a data set of countries, it would be most helpful to have an initial and common data set of organisations.
Even if the constituencies of opencti users are distinct, still, the main sources of opensource information are the same.

This could include:
- a list of CSIRT / NCSC / LE (e.g. ANSSI, CERT-EU, NCSC-UK, CERT-Bund, Europol, FBI, etc)
- a list of IT security vendors (Symantec, McAfee, Checkpoint, Kaspersky, FireEye, Trendmicro, Proofpoint, Cylance, Telsy, Recorded Future, BAE systems, ESET, Crowdstrike, FireEye, etc)
- a list of IT security resources (Infosecurity, Bleeping computer, ZDnet, Security affairs, Threat post, malwarebytes, Alienvault, etc)
- a list news papers or press agencies known to release articles on cyber threats (Reuters, The New York Tims, The Guardian, etc)

**Comment by DocArmoryTech** [comment]
The "[Cerebrate project](https://github.com/cerebrate-project/cerebrate)" would seem to satisfy some of the requirements outlined - would a "cerebrate-connector" to a cerebrate server suffice? 
or is the intention herein to have a downloadable, maintained, list of organisations ?

**Comment by SamuelHassine** [comment]
Done.
